#!/usr/bin/env bash
# bxPlaywright bash completions. Generated by `bxPlaywright completions`, do not edit.
_bxplaywright_complete() {
	local cur verb
	cur="${COMP_WORDS[COMP_CWORD]}"
	verb="${COMP_WORDS[1]}"
	if [[ ${COMP_CWORD} -eq 1 ]]; then
		COMPREPLY=( $(compgen -W "clean codegen completions devices doctor help install install-deps install-node mcp open pdf profiles run screenshot show-trace uninstall version --help --version" -- "$cur") )
		return 0
	fi
	case "$verb" in
		clean) COMPREPLY=( $(compgen -W "--json" -- "$cur") ) ;;
		codegen) COMPREPLY=( $(compgen -W "--output --target --device --viewport-size --load-storage --save-storage" -- "$cur") ) ;;
		completions) COMPREPLY=( $(compgen -W "" -- "$cur") ) ;;
		devices) COMPREPLY=( $(compgen -W "--json" -- "$cur") ) ;;
		doctor) COMPREPLY=( $(compgen -W "--json" -- "$cur") ) ;;
		help) COMPREPLY=( $(compgen -W "--json clean codegen completions devices doctor help install install-deps install-node mcp open pdf profiles run screenshot show-trace uninstall version" -- "$cur") ) ;;
		install) COMPREPLY=( $(compgen -W "--with-deps --only-shell --force --skip-node --json chromium firefox webkit chrome chrome-beta msedge all" -- "$cur") ) ;;
		install-deps) COMPREPLY=( $(compgen -W "chromium firefox webkit chrome chrome-beta msedge all" -- "$cur") ) ;;
		install-node) COMPREPLY=( $(compgen -W "--force --json" -- "$cur") ) ;;
		mcp) COMPREPLY=( $(compgen -W "--headless --browser --port" -- "$cur") ) ;;
		open) COMPREPLY=( $(compgen -W "--device --browser" -- "$cur") ) ;;
		pdf) COMPREPLY=( $(compgen -W "--paper-format" -- "$cur") $(compgen -f -- "$cur") ) ;;
		profiles) COMPREPLY=( $(compgen -W "--json 4k android android-tablet chrome chrome-beta chromium ci dark debug default desktop edge firefox galaxy hd headed high-contrast ipad iphone iphone-se laptop light macbook mobile mobile-landscape offline pixel print record reduced-motion screenshot tablet webkit" -- "$cur") ) ;;
		run) COMPREPLY=( $(compgen -W "" -- "$cur") ) ;;
		screenshot) COMPREPLY=( $(compgen -W "--full-page --device --browser" -- "$cur") $(compgen -f -- "$cur") ) ;;
		show-trace) COMPREPLY=( $(compgen -W "" -- "$cur") $(compgen -f -- "$cur") ) ;;
		uninstall) COMPREPLY=( $(compgen -W "--all" -- "$cur") ) ;;
		version) COMPREPLY=( $(compgen -W "--json" -- "$cur") ) ;;
		*) COMPREPLY=() ;;
	esac
}
complete -F _bxplaywright_complete bxPlaywright
